const mockTasks = [
  {
    id: 10001,
    project: "Project A",
    title: "Fix login bug",
    description: "Resolve issue with user login on mobile.",
    assignee: "Rahul Sharma",
    priority: "High",
    status: "Assigned",
    type: "Bug",
    createdAt: "2025-06-05",
    activeStartTime: null,
    closedAt: null,
    timeSpent: null,
  },
  {
    id: 10002,
    project: "Project B",
    title: "Add password reset",
    description: "Implement password reset flow for users.",
    assignee: "Priya Verma",
    priority: "Medium",
    status: "Active",
    type: "Task",
    createdAt: "2025-06-04",
    activeStartTime: Date.now() - 600000, 
    closedAt: null,
    timeSpent: null,
  },
  {
    id: 10003,
    project: "Project A",
    title: "Create landing page",
    description: "Design and build landing page.",
    assignee: "Amit Kumar",
    priority: "Low",
    status: "Close",
    type: "Task",
    createdAt: "2025-06-02",
    activeStartTime: null,
    closedAt: Date.now() - 86400000, 
    timeSpent: "01:20:00",
  },
  {
    id: 10004,
    project: "Project C",
    title: "Update dashboard",
    description: "Add new filters and sorting options.",
    assignee: "Anjali Singh",
    priority: "High",
    status: "Active",
    type: "Task",
    createdAt: "2025-06-07",
    activeStartTime: Date.now() - 300000, 
    closedAt: null,
    timeSpent: null,
  },
  {
    id: 10005,
    project: "Project B",
    title: "Fix sidebar overflow",
    description: "Handle overflow in sidebar navigation.",
    assignee: "Rohit Gupta",
    priority: "Medium",
    status: "Assigned",
    type: "Bug",
    createdAt: "2025-06-03",
    activeStartTime: null,
    closedAt: null,
    timeSpent: null,
  },
  {
    id: 10006,
    project: "Project C",
    title: "Refactor API calls",
    description: "Improve performance of API requests.",
    assignee: "Rahul Sharma",
    priority: "Low",
    status: "Assigned",
    type: "Task",
    createdAt: "2025-06-08",
    activeStartTime: null,
    closedAt: null,
    timeSpent: null,
  },
  {
    id: 10007,
    project: "Project A",
    title: "Add dark mode",
    description: "Add dark mode support to UI.",
    assignee: "Priya Verma",
    priority: "Medium",
    status: "Close",
    type: "Task",
    createdAt: "2025-06-06",
    activeStartTime: null,
    closedAt: Date.now() - 43200000,
    timeSpent: "00:45:00",
  },
];

export default mockTasks;